name: CI

# on:
#   schedule:
#   - cron: "0 2 * * *"

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: dnsvalidator
      uses: docker://s14ve/dnsvalidator:1.0
      with:
        args: '-tL https://public-dns.info/nameservers.txt -threads 15 -o resolvers.txt'
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resolvers.txt
        git commit -m "Update resolvers" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
