name: CI

# on:
#   schedule:
#   - cron: "0 2 * * *"

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test cat
      run: |
        git clone https://github.com/vortexau/dnsvalidator
        cd dnsvalidator
        pip3 install wheel
        pip3 install setuptools
        python3 setup.py install
        dnsvalidator/dnsvalidator.py -tL https://public-dns.info/nameservers.txt -threads 15 -o ../resolvers.txt
        head ../resolvers.txt
    - name: test cat
      run: |
        head resolvers.txt
        head ../resolvers.txt
    - name: test1 cat
      run: cat test1.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resolvers.txt
        git commit -m "Update resolvers" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
