name: CI

# on:
#   schedule:
#   - cron: "0 2 * * *"

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test cat
      run: echo test > test.txt || cat test.txt
    - name: dnsvalidator
      uses: docker://alpine
      with:
        args: 'echo test > test1.txt || cat test1.txt'
    - name: test cat
      run: cat test.txt
    - name: test cat
      run: cat test1.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resolvers.txt
        git commit -m "Update resolvers" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
